### ISSUE TITLE
Missing configuration settings

### ISSUE THREAD

**Issue by stonar96** [EngineHub/WorldGuardDocs#18]
**Not documented but present in the config.yml:**
```yml
custom-metrics-charts: true
disable-permission-cache: false
extra-timings:
    session-handlers: true
gameplay:
    disable-conduit-effects: false
mobs:
    block-armor-stand-destroy: false
    block-vehicle-entry: false
protection:
    disable-obsidian-generators: false
    use-max-priority-association: false # documented in #16
regions:
    cancel-chat-without-recipients: true
    location-flags-only-inside-regions: false
    nether-portal-protection: true
security:
    host-keys-allow-forge-clients: false
use-particle-effects: true
weather:
    disable-villager-witchification: false
```

**Not documented but present in the per-world config.yml:**
```yml
regions:
    titles-always-use-default-times: true
```

**Documented but not present in the config.yml:**
```yml
regions:
    use-scheduler: true
```

**Not correctly documented:**
```yml
regions:
    wand: minecraft:leather # documented as leather
```
